### ISSUE TITLE
TypeScript transpiling fails due to missing dependencies

### ISSUE THREAD

**Issue by slawekzachcial** [OfficeDev/Orky#15]
Hello. When trying to deploy Orky Bot on Azure I got errors about missing dependencies.

Since those dependencies seem to be defined in `devDependencies` section of `package.json` I was able to make it work by changing `deploy.cmd` and removing `--production` from `npm install` command. I realize that the intent of `devDependencies` is different from `dependencies` and my approach may be incorrect.

**Comment by MattSFT** [comment]
The current deployment had azure transpiling the typescript on deploy. The correct way to do it would be to have a build system do the transpilation and azure to just do the deployment but this is much easier.... So while typescript is technically a dev dependency, azure needs it and you did the right thing. Could you submit  a pr to remove the production bit from deployment command?
